### ISSUE TITLE
1# Nema validacije u izmjeni korisničkih podataka(front i back)

### ISSUE THREAD

**Issue by etfgunner** [SoftverInzenjeringETFSA/SI2016_TIM14#1]
Komponenta: ..controllers/edit-profile.js

Commit ID: e68fa26629c4ed5d01e2e4606fcc6f8e7a788e9

Opis problema: Nakon logina, moguće je promjeniti podatke bez ikakve validacije. Npr. u ime je moguće staviti bilo kakav znak, a e-mail adresa se može promjeniti  na bilo kakvo slovo(ne mora biti oblika username@example.com). Ovako to izgleda:  http://imgur.com/a/RGZxD

Koraci koji vode do greške:
1. Pokretanje aplikacije
2. Login(Registracija)
3. Klik na button 'edit profile'
4. Dodavanje bilo kakvih  podataka koji ne bi smjeli biti sačuvani
5. Save

**Comment by emilisic1** [comment]
Kakve veze ima email adresa, sa editom profila? Korisnik može tehnički pisati šta hoće na svoj profil, jer nemamo nikakav policy koji bi mu to zabranio.

**Comment by etfgunner** [comment]
Ime i prezime bi trebali biti validirani da ne piše nešto tipa .fčasd.fšas[<f>@dfsa\, ovo valjda nije validno ime. Što se tiče e-mail adrese, tu sam vam dao hint da validirate e-mail adresu, jer je validirana u registraciji(a valjda treba biti ista validacija i tu), a ima i još jedan razlog: https://pasteboard.co/fofS82ZVd.png
U ovom FZ, piše da e-mail adresa mora biti jedinstvena. Sad ja mogu napraviti 10 profila i izmjeniti podatke da tako svi imaju isti e-mail, što se ne bi smjelo desiti.

**Comment by emilisic1** [comment]
Aha, aha, okej, sad je jasnije.

**Comment by emilisic1** [comment]
Issue fixed with commid ID:  6a84047
