### ISSUE TITLE
Grupa radio/check buttona ispod avatara - ne radi ništa ?

### ISSUE THREAD

**Issue by JasminkoVidakovic** [SoftverInzenjeringETFSA/SI2016_TIM14#10]
Komponenta: ..controllers/profil.js
CommitID: 7b76662

Na "My Profile" page-u, ispod avatara, nalazi se grupa od 5 radio/check buttona, čija funkcionalnost nije objašnjenja, nema nikakve vidljive akcije prilikom interackije s istima, nije navedeno u SRS-u ništa vezano za ovo.

Screenshot: http://pokit.org/get/?425467a281736fc891ec14e2fb93b905.jpg

Koraci koji vode do greške:

- Pokretanje aplikacije
- Login/Registracija
- Redirect na "My Profile" page
- Interakcija sa buttonima

**Comment by emilisic1** [comment]
@dybrom ukini ovo skroz.

**Comment by emilisic1** [comment]
Fixed with commit ID: f631966
