### ISSUE TITLE
Nemogućnost prihvatanja zahtjeva za chat

### ISSUE THREAD

**Issue by JasminkoVidakovic** [SoftverInzenjeringETFSA/SI2016_TIM14#11]
Komponenta: ..controllers/invites.js
CommitID: 4b7649a 

Prema SRS-u, funkcionalni zahtjev 3.2.7, treba biti moguće i odbiti i prihvatiti zahtjev za chat, međutim nije implementirano da se zahtjev može prihvatiti.

Screenshot reference: http://pokit.org/get/?15549b7f5755dc64125e75f4142b2fb1.jpg

Koraci koji vode do greške:

- Pokretanje aplikacije
- Login/Registracija
- Redirect na "My Profile" page
- Navigacija na "Private Messages"->All Chat Requests
- Pokušaj da se prihvati postojeći zahjtev

**Comment by amilojevic** [comment]
Fixed in commit:  c467986
