### ISSUE TITLE
Dizajn: 2.3- ERD

### ISSUE THREAD

**Issue by etfgunner** [SoftverInzenjeringETFSA/SI2016_TIM14#15]
Komponenta: docs/dizajn.pdf

Commit ID: dbf8efad5ac05af31c4116c059eacc83a

Opis problema: U ERD-u se nalazi tabela PrivateChatArchive, koja se ne spominje u FZ.

Koraci koji vode do greške:

1. Otvaranje dizajna
2. Otvaranje SRS-a
3. Uočavanje razlika

**Comment by emilisic1** [comment]
Solved by commit ID:  a76fe1b
