### ISSUE TITLE
Baza- Tabela private chat

### ISSUE THREAD

**Issue by etfgunner** [SoftverInzenjeringETFSA/SI2016_TIM14#16]
Komponenta: baza

Commit ID: d422f1cea98e517937f0e01c1ed28ca42d353195

Opis problema: U ERD-u, u tabeli Private chat se nalazi polje Message, dok u bazi to polje nedostaje(čime se ne mogu bilježiti poslane poruke)..

Koraci koji vode do greške:

1. Otvaranje baze
2. Otvaranje dizajna

**Comment by emilisic1** [comment]
Solved by commit ID:  a76fe1b
