### ISSUE TITLE
Problem navigacije sa Login stranice kada je korisnik logovan

### ISSUE THREAD

**Issue by JasminkoVidakovic** [SoftverInzenjeringETFSA/SI2016_TIM14#18]
Komponenta: ..controllers/login.js
CommitID:  8e68fa2

U slučaju kada je korisnik logovan, ako se ponovo pristupi lokaciji localhost:4200, korisnik je stuck na Login page-u i nema mogućnost da se navigira kroz ostale podstranice platforme.

Screenshot: http://pokit.org/get/?2b1d8aabd123666aa9d28df009e7131f.jpg

Koraci koji vode do greške:

- Pokretanje aplikacije
- Login
- Ponovni pristup Login pageu (reloadanje aplikacije)

**Comment by amilojevic** [comment]
Ispravljeno u commitId-u: dc28e8e
