### ISSUE TITLE
Administrator je u stanju izbrisati sam sebe iz usera i DB-a

### ISSUE THREAD

**Issue by JasminkoVidakovic** [SoftverInzenjeringETFSA/SI2016_TIM14#19]
Komponenta: ..controllers/view-all-users.js
CommitID:  69e54ad

Korisnik, koji je logovan na platformu kao admin, je na admin. panelu za brisanje korisnika u stanju obrisati sam sebe. U slučaju kada je taj korisnik ujedno i jedini administrator na platformi, kako je bilo sa testnim podacima, nakon brisanja samog sebe platforma je ostala bez administratora, što predstavlja u krajnjem slučaju sigurnosni problem.

Koraci koji vode do greške:

- Pokretanje aplikacije
- Login kao administrator
- Pristup na "Admin Panel"
- Navigacija na "View All Users"
- Admin briše sam sebe

**Comment by amilojevic** [comment]
Fixed bug using a method allExceptMe CommitId:  8e24148
