### ISSUE TITLE
#2 Pristup funkcionalnostima iako korisnik nije logovan

### ISSUE THREAD

**Issue by etfgunner** [SoftverInzenjeringETFSA/SI2016_TIM14#2]
Komponenta: ..controllers/profil.js

Commit ID: 7b7666229b117b23affb1ed5726e7cb8b6f97184

Opis problema: (FZ 3.2.4- Preduslov nije ispunjen) Nakon logina, korisnik se preusmjerava na localhost:4200/profil. Nakon toga, korisnik se može logout i ukucati localhost:4200/profil nakon čega se ta stranica otvori kao i logovanom korisniku. Sve mogućnosti koje ima logovani korisnik, na ovaj način ima i anonymous.  Ovako to izgleda: http://imgur.com/a/MfzZP

Koraci koji vode do greške:

1.Pokretanje aplikacije
2. Ukucati u link; localhost:4200/profil (bez logina)

**Comment by amilojevic** [comment]
Ispravljeno u commitId-u: dc28e8e
