### ISSUE TITLE
#3 Nepostojanje povratne informacije o prihvaćenom ili odbijenom zahtjevu za chat 

### ISSUE THREAD

**Issue by lzecevic1** [SoftverInzenjeringETFSA/SI2016_TIM14#4]
Komponenta: /controllers/UserController.java

Commit ID:  [4b7649a353cad00fba585fa710a94206e29c7db2](https://github.com/SoftverInzenjeringETFSA/SI2016_TIM14/commit/4b7649a353cad00fba585fa710a94206e29c7db2)

Opis problema: Kada korisnik primi zahtjev za chat i isti odbije, korisnik koji je poslao zahtjev ne dobije nikakvu obavijest o tome. Na ovaj način se narušava Funkcionalni zahtjev 3.2.7, prema kojem je izlaz: "Prikaz chat pregleda u slučaju prihvatanja ili poruka o odbijanju".

Koraci koji vode do greške:
- Prijava na sistem
- Odabir opcije _Invite users_
- Odabir korisnika s kojim se želi ostvariti komunikacija, te klik na dugme _invite_
-Korisnik kojem je poslan zahtjev mora biti prijavljen na sistem
-Odabirom opcije _Private Messages_, a zatim _All Chat Requests_ pregleda sve zahtjeve za chat
-Odabirom opcije _Decline_ na određeni request korisnik odbija zahtjev za chat
-Korisnik koji je poslao zahtjev ne dobija nikakvu obavijest o tome da je druga osoba odbila njegov zahtjev.

**Comment by amilojevic** [comment]
Fixed in commitId:  d394c4e
