### ISSUE TITLE
Nedostatak podstranice za FAQ, kontakt i HelpDesk

### ISSUE THREAD

**Issue by JasminkoVidakovic** [SoftverInzenjeringETFSA/SI2016_TIM14#6]
Komponenta: ..controllers/application.js
CommitID: 5614b5b

U SRS-u je po nefunkcionalnom zahtjevu NFZ2 predviđeno da će platforma nuditi podstranicu sa FAQ, kontaktom i help-centrom, da će to biti dostupno na svakoj podstranici, a to nije realizirano.

Koraci koji vode do greške:

- Pokretanje aplikacije
- Login(Registracija)
- Navigacija na bilo koju podstranicu, u cilju traženja pomenute funkcionalnosti

**Comment by emilisic1** [comment]
Fixed with commit ID:  f631966.
